2021-11-02 16:00:13.172455: W external/org_tensorflow/tensorflow/compiler/xla/service/platform_util.cc:205] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/home/qiyang/.local/lib/python3.6/site-packages/jaxlib/xla_client.py", line 161, in get_local_backend
    return backends[name]
KeyError: 'gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiyang/source/jaxgfpeps//src/main.py", line 36, in <module>
    method="L-BFGS-B", jac=True, options={'gtol': 1e-07,'maxiter': 1000,'disp':True})
  File "/home/qiyang/.local/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 610, in minimize
    callback=callback, **options)
  File "/home/qiyang/.local/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 345, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/qiyang/.local/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 295, in func_and_grad
    f = fun(x, *args)
  File "/home/qiyang/.local/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 327, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/qiyang/.local/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 65, in __call__
    fg = self.fun(x, *args)
  File "/home/qiyang/source/jaxgfpeps//src/main.py", line 32, in val_grad_R
    value, grad = value_and_grad(lossR)(jnp.reshape(jnp.array(R),(Rsize,Rsize)))
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/api.py", line 823, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args)
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/api.py", line 1896, in _vjp
    out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/interpreters/ad.py", line 114, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/interpreters/ad.py", line 101, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 506, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/api.py", line 416, in f_jitted
    return cpp_jitted_f(context, *args, **kwargs)
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/api.py", line 351, in get_device_info
    backend_ = xb.get_backend(backend)
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/lib/xla_bridge.py", line 178, in get_backend
    return backend(platform)
  File "/home/qiyang/.local/lib/python3.6/site-packages/jax/lib/xla_bridge.py", line 130, in _get_local_backend
    backend = xla_client.get_local_backend(platform)
  File "/home/qiyang/.local/lib/python3.6/site-packages/jaxlib/xla_client.py", line 164, in get_local_backend
    'Unknown backend %s. Available: %s' % (name, list(backends.keys())))
RuntimeError: Unknown backend gpu. Available: ['interpreter', 'cpu']
 This problem is unconstrained.
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =          144     M =           10

At X0         0 variables are exactly at the bounds
